In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

In [12]:
credit_data = pd.read_csv("C:\\Users\\mpucci\\Desktop\\Credit.csv",
                          usecols = ["Income","Limit","Rating","Cards","Age","Education","Gender","Student","Married",
                                    "Ethnicity","Balance"])


In [13]:
print(credit_data.isna().sum()) #No NaN Values in DataSet
print (credit_data.shape) #400 rows with 11 columns

Income       0
Limit        0
Rating       0
Cards        0
Age          0
Education    0
Gender       0
Student      0
Married      0
Ethnicity    0
Balance      0
dtype: int64
(400, 11)


In [14]:
X = credit_data[["Income","Limit","Rating","Cards","Age","Education"]] #Attribute Matrix 

In [15]:
credit_data["Balance_Boolean"] = credit_data["Balance"]<=1500

In [16]:
credit_data['Balance_factor'] = credit_data["Balance_Boolean"].factorize()[0]
print(credit_data)
credit_data1 = credit_data.copy()


      Income  Limit  Rating  Cards  Age  Education  Gender Student Married  \
0     14.891   3606     283      2   34         11    Male      No     Yes   
1    106.025   6645     483      3   82         15  Female     Yes     Yes   
2    104.593   7075     514      4   71         11    Male      No      No   
3    148.924   9504     681      3   36         11  Female      No      No   
4     55.882   4897     357      2   68         16    Male      No     Yes   
5     80.180   8047     569      4   77         10    Male      No      No   
6     20.996   3388     259      2   37         12  Female      No      No   
7     71.408   7114     512      2   87          9    Male      No      No   
8     15.125   3300     266      5   66         13  Female      No      No   
9     71.061   6819     491      3   41         19  Female     Yes     Yes   
10    63.095   8117     589      4   30         14    Male      No     Yes   
11    15.045   1311     138      3   64         16    Male      

In [17]:
credit_data.drop(['Balance_Boolean'],axis=1)

Income  Limit  Rating  Cards  Age  Education  Gender Student Married  \
0     14.891   3606     283      2   34         11    Male      No     Yes   
1    106.025   6645     483      3   82         15  Female     Yes     Yes   
2    104.593   7075     514      4   71         11    Male      No      No   
3    148.924   9504     681      3   36         11  Female      No      No   
4     55.882   4897     357      2   68         16    Male      No     Yes   
5     80.180   8047     569      4   77         10    Male      No      No   
6     20.996   3388     259      2   37         12  Female      No      No   
7     71.408   7114     512      2   87          9    Male      No      No   
8     15.125   3300     266      5   66         13  Female      No      No   
9     71.061   6819     491      3   41         19  Female     Yes     Yes   
10    63.095   8117     589      4   30         14    Male      No     Yes   
11    15.045   1311     138      3   64         16    Male      No      No   
12    80.616   5308     394      1   57          7  Female      No     Yes   
13    43.682   6922     511      1   49          9    Male      No     Yes   
14    19.144   3291     269      2   75         13  Female      No      No   
15    20.089   2525     200      3   57         15  Female      No     Yes   
16    53.598   3714     286      3   73         17  Female      No     Yes   
17    36.496   4378     339      3   69         15  Female      No     Yes   
18    49.570   6384     448      1   28          9  Female      No     Yes   
19    42.079   6626     479      2   44          9    Male      No      No   
20    17.700   2860     235      4   63         16  Female      No      No   
21    37.348   6378     458      1   72         17  Female      No      No   
22    20.103   2631     213      3   61         10    Male      No     Yes   
23    64.027   5179     398      5   48          8    Male      No     Yes   
24    10.742   1757     156      3   57         15  Female      No      No   
25    14.090   4323     326      5   25         16  Female      No     Yes   
26    42.471   3625     289      6   44         12  Female     Yes      No   
27    32.793   4534     333      2   44         16    Male      No      No   
28   186.634  13414     949      2   41         14  Female      No     Yes   
29    26.813   5611     411      4   55         16  Female      No      No   
..       ...    ...     ...    ...  ...        ...     ...     ...     ...   
370   35.610   6135     466      4   40         12    Male      No      No   
371   39.116   2150     173      4   75         15    Male      No      No   
372   19.782   3782     293      2   46         16  Female     Yes      No   
373   55.412   5354     383      2   37         16  Female     Yes     Yes   
374   29.400   4840     368      3   76         18  Female      No     Yes   
375   20.974   5673     413      5   44         16  Female      No     Yes   
376   87.625   7167     515      2   46         10  Female      No      No   
377   28.144   1567     142      3   51         10    Male      No     Yes   
378   19.349   4941     366      1   33         19    Male      No     Yes   
379   53.308   2860     214      1   84         10    Male      No     Yes   
380  115.123   7760     538      3   83         14  Female      No      No   
381  101.788   8029     574      2   84         11    Male      No     Yes   
382   24.824   5495     409      1   33          9    Male     Yes      No   
383   14.292   3274     282      9   64          9    Male      No     Yes   
384   20.088   1870     180      3   76         16    Male      No      No   
385   26.400   5640     398      3   58         15  Female      No      No   
386   19.253   3683     287      4   57         10    Male      No      No   
387   16.529   1357     126      3   62          9    Male      No      No   
388   37.878   6827     482      2   80         13  Female      No      No   
389   83.948   7100     503 

In [18]:
counter = 0 
for balance in credit_data.Balance_factor:
    if balance == 1: 
        counter+=1
print ((counter/400)*100) # percentage of trues in dataset. 

2.25


In [19]:
print("This is the Logisitic Regression Fit")

X = credit_data[['Income','Limit', 'Rating', 'Cards', 'Age', 'Education']]
y = credit_data['Balance_factor']
lr = LogisticRegression()
lr.fit(X, y)

print(lr.intercept_)
print(lr.coef_)

This is the Logisitic Regression Fit
[-0.81363578]
[[-0.00950572  0.00499434 -0.05897994  0.11851539 -0.05977501 -0.35404606]]


In [20]:
print("This is the LDA fit equation")

X = credit_data[['Income','Limit', 'Rating', 'Cards', 'Age', 'Education']]
y = credit_data['Balance_factor']

lda = LinearDiscriminantAnalysis()
lda.fit(X,y)

print(lda.intercept_)
print(lda.coef_)

This is the LDA fit equation
[-14.25754044]
[[ 2.50503328e-02 -2.46350024e-04  1.90771457e-02  2.92958512e-01
  -1.61624107e-02 -1.68504978e-02]]


In [21]:
print("This is the Quadratic Fit")

X = credit_data[['Income','Limit', 'Rating', 'Cards', 'Age', 'Education']]
y = credit_data['Balance_factor']

qda = QuadraticDiscriminantAnalysis()
qda.fit(X,y)


This is the Quadratic Fit


QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
               store_covariance=False, store_covariances=None, tol=0.0001)

In [22]:
print("Logistic regression equation and prediction")

X1_pred = np.array([63,8100,600,4,30,14]).reshape(-1,6)

print(lr.predict_proba(X1_pred))

X2_pred = np.array([186,13414,950,2,41,13]).reshape(-1,6)

print(lr.predict_proba(X2_pred))

#x1= 'Income' = 63, 'Limit' = 8100, 'Rating' = 600, 'Cards' = 4, 'Age' = 30, 'Education' =14

#x2= ['Income' = 186, 'Limit' = 13414, 'Rating' = 950, 'Cards' = 2, 'Age' = 41, 'Education' =13

Logistic regression equation and prediction
[[0.93227393 0.06772607]]
[[0.1729211 0.8270789]]


In [23]:
print("LDA fit equation and prediction")

X1_pred = np.array([63,8100,600,4,30,14]).reshape(-1,6)

print(lda.predict_proba(X1_pred))

X2_pred = np.array([186,13414,950,2,41,13]).reshape(-1,6)

print(lda.predict_proba(X2_pred))

LDA fit equation and prediction
[[0.94144572 0.05855428]]
[[0.00721199 0.99278801]]


In [24]:
print("QDA fit equation and prediction")
X1_pred = np.array([63,8100,600,4,30,14]).reshape(-1,6)

print(qda.predict_proba(X1_pred))

X2_pred = np.array([186,13414,950,2,41,13]).reshape(-1,6)

print(qda.predict_proba(X2_pred))

QDA fit equation and prediction
[[9.99999999e-01 1.24419207e-09]]
[[7.83057752e-04 9.99216942e-01]]


In [30]:
'''After performing a logisitic regression, the probability associated to x1 vector having a balance less than 1500 was 93.2% 
compared to having 6.8% chance of having a balance of greater than 1500. 

After performing a logisitic regression, the probability associated to x2 vector having a balance less than 1500 was 17.3% 
compared to having 82.7% chance of having a balance of greater than 1500. 

After performing a linear discriminant analysis, the probability associated to x1 vector having a balance less than 1500 
was 94.1% compared to having 5.9% chance of having a balance of greater than 1500. 

After performing a linear discriminant analysis, the probability associated to x2 vector having a balance less than 1500 
was 0.7% compared to having 99.3% chance of having a balance of greater than 1500. 

After performing a quadratic discriminant analysis, the probability associated to x1 vector having a balance less than 1500
was 99.9% compared to having 0.01% chance of having a balance of greater than 1500. 

After performing a quadratic discriminant analysis, the probability associated to x2 vector having a balance less than 1500 
was 0.01% compared to having 99.9% chance of having a balance of greater than 1500. 

If we focus on the linear and quadratic discriminant analysis, LDA is an analysis that uses a linear decision-making
surface whereas QDA uses a Quadric decision making surface. Furthermore, we see that the assumption that the features 
in our model do not share a common variance, may have overfitted the QDA model and even though has made it extremely flexible, 
seems to have introduce a high degree of bias. This is from the fact that the classification are near perfect for both x1 and x2. 

Therefore, the assumption that the features share a common covariance matrix holds well since there is more seperation amongst 
the classification probabilities we received. In addition, due to the small feature size, it is imperative to minmize the 
variance between our features. This is indeed the outcome of running a LDA model. Additionally, this privdes explanation
to why when there a few traiing observations, reductionality of variance is imperative and hence why LDA would be 
a better fit compared to DQA for this example. 

Lastly, for the logistic regression, the classification for balance appear to be reasonable classification. Compared to the 
traning set percentage of 2.25% true to have a balance over 1500, the initial logistic regression classifications do not seem to 
be as accurate as the LDA outputs. However, this leads me to think that the default cut off for the logistic model may not be
best fit for this scenario. Tuning of these parameters could provide more informational insight and a more accurate classification
prediciton. '''


'After performing a logisitc regression, the probability associated to x1 vector having a balance less than 1500 was 93.2% \ncompared to having 6.8% chance of having a balance of greater than 1500. \n\nAfter performing a logisitc regression, the probability associated to x2 vector having a balance less than 1500 was 17.3% \ncompared to having 82.7% chance of having a balance of greater than 1500. \n\nAfter performing a linear discriminant analysis, the probability associated to x1 vector having a balance less than 1500 \nwas 94.1% compared to having 5.9% chance of having a balance of greater than 1500. \n\nAfter performing a linear discriminant analysis, the probability associated to x2 vector having a balance less than 1500 \nwas 0.7% compared to having 99.3% chance of having a balance of greater than 1500. \n\nAfter performing a quadratic discriminant analysis, the probability associated to x1 vector having a balance less than 1500\nwas 99.9% compared to having 0.01% chance of having